### ISSUE TITLE
Does not work without mumble open

### ISSUE THREAD

**Issue by victoroux** [Superritchman/gw2-portalcounter#12]
Not sure if this is required or not, but in my case it won't show the range difference unless I open mumble separately. Would be nice if we can use the program without mumble

**Comment by Superritchman** [comment]
It shouldn't be necessary to use mumble.
This bug should be fixed in [Version 1.2.3](https://github.com/Superritchman/gw2-portalcounter/releases/tag/v1.2.3).
Please try [Version 1.3](https://github.com/Superritchman/gw2-portalcounter/releases/tag/v1.3) and report me if the bug still occure.

**Comment by victoroux** [comment]
fixed in 1.3 -- good work!
